namespace Yawnese.Emulator
{
    partial class Cpu
    {
        static readonly string[] INSTRUCTION_NAMES = {
            "BRK", "ORA", "KIL", "SLO", "NOP", "ORA", "ASL", "SLO", "PHP", "ORA", "ASL", "ANC", "NOP",
            "ORA", "ASL", "SLO", "BPL", "ORA", "KIL", "SLO", "NOP", "ORA", "ASL", "SLO", "CLC", "ORA",
            "NOP", "SLO", "NOP", "ORA", "ASL", "SLO", "JSR", "AND", "KIL", "RLA", "BIT", "AND", "ROL",
            "RLA", "PLP", "AND", "ROL", "ANC", "BIT", "AND", "ROL", "RLA", "BMI", "AND", "KIL", "RLA",
            "NOP", "AND", "ROL", "RLA", "SEC", "AND", "NOP", "RLA", "NOP", "AND", "ROL", "RLA", "RTI",
            "EOR", "KIL", "SRE", "NOP", "EOR", "LSR", "SRE", "PHA", "EOR", "LSR", "ALR", "JMP", "EOR",
            "LSR", "SRE", "BVC", "EOR", "KIL", "SRE", "NOP", "EOR", "LSR", "SRE", "CLI", "EOR", "NOP",
            "SRE", "NOP", "EOR", "LSR", "SRE", "RTS", "ADC", "KIL", "RRA", "NOP", "ADC", "ROR", "RRA",
            "PLA", "ADC", "ROR", "ARR", "JMP", "ADC", "ROR", "RRA", "BVS", "ADC", "KIL", "RRA", "NOP",
            "ADC", "ROR", "RRA", "SEI", "ADC", "NOP", "RRA", "NOP", "ADC", "ROR", "RRA", "NOP", "STA",
            "NOP", "SAX", "STY", "STA", "STX", "SAX", "DEY", "NOP", "TXA", "XAA", "STY", "STA", "STX",
            "SAX", "BCC", "STA", "KIL", "AHX", "STY", "STA", "STX", "SAX", "TYA", "STA", "TXS", "TAS",
            "SHY", "STA", "SHX", "AHX", "LDY", "LDA", "LDX", "LAX", "LDY", "LDA", "LDX", "LAX", "TAY",
            "LDA", "TAX", "LAX", "LDY", "LDA", "LDX", "LAX", "BCS", "LDA", "KIL", "LAX", "LDY", "LDA",
            "LDX", "LAX", "CLV", "LDA", "TSX", "LAS", "LDY", "LDA", "LDX", "LAX", "CPY", "CMP", "NOP",
            "DCP", "CPY", "CMP", "DEC", "DCP", "INY", "CMP", "DEX", "AXS", "CPY", "CMP", "DEC", "DCP",
            "BNE", "CMP", "KIL", "DCP", "NOP", "CMP", "DEC", "DCP", "CLD", "CMP", "NOP", "DCP", "NOP",
            "CMP", "DEC", "DCP", "CPX", "SBC", "NOP", "ISB", "CPX", "SBC", "INC", "ISB", "INX", "SBC",
            "NOP", "SBC", "CPX", "SBC", "INC", "ISB", "BEQ", "SBC", "KIL", "ISB", "NOP", "SBC", "INC",
            "ISB", "SED", "SBC", "NOP", "ISB", "NOP", "SBC", "INC", "ISB",
        };

        static readonly ushort[] INSTRUCTION_SIZES = {
            1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
            3, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
            1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
            1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
            2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 1, 3, 3, 3, 3,
            2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
            2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
            2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3,
        };

        static readonly Mode[] INSTRUCTION_MODES = {
            Mode.NotAvailable, // 0x00
            Mode.IndirectX,
            Mode.NotAvailable,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Accumulator,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0x10
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.Absolute, // 0x20
            Mode.IndirectX,
            Mode.NotAvailable,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Accumulator,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0x30
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.NotAvailable, // 0x40
            Mode.IndirectX,
            Mode.NotAvailable,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Accumulator,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0x50
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.NotAvailable, // 0x60
            Mode.IndirectX,
            Mode.NotAvailable,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Accumulator,
            Mode.Immediate,
            Mode.Indirect,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0x70
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.Immediate, // 0x80
            Mode.IndirectX,
            Mode.Immediate,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0x90
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageY,
            Mode.ZeroPageY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteY,
            Mode.AbsoluteY,
            Mode.Immediate, // 0xA0
            Mode.IndirectX,
            Mode.Immediate,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0xB0
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageY,
            Mode.ZeroPageY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteY,
            Mode.AbsoluteY,
            Mode.Immediate, // 0xC0
            Mode.IndirectX,
            Mode.Immediate,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0xD0
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.Immediate, // 0xE0
            Mode.IndirectX,
            Mode.Immediate,
            Mode.IndirectX,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.ZeroPage,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.NotAvailable,
            Mode.Immediate,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Absolute,
            Mode.Relative, // 0xF0
            Mode.IndirectY,
            Mode.NotAvailable,
            Mode.IndirectY,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.ZeroPageX,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.NotAvailable,
            Mode.AbsoluteY,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
            Mode.AbsoluteX,
        };
    }
}